name: Publish to NPM registry

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm and install dependencies
        uses: pnpm/action-setup@v4
        with:
         version: latest

      - name: Publish package
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}